#include <oesdk/elf_loader.h>
#include <string.h>
#define PT_LOAD 1U
#define PF_X 1U
#define PF_W 2U
typedef struct __attribute__((packed)){unsigned char Ident[16];uint16_t Type,Machine;uint32_t Version;uint64_t Entry,Phoff,Shoff;uint32_t Flags;uint16_t Ehsize,Phentsize,Phnum,Shentsize,Shnum,Shstrndx;} Ehdr;
typedef struct __attribute__((packed)){uint32_t Type,Flags;uint64_t Offset,Vaddr,Paddr,Filesz,Memsz,Align;} Phdr;
static bool AddOk(uint64_t A,uint64_t B,uint64_t*R){if(B>UINT64_MAX-A)return false;*R=A+B;return true;}
OesdkStatus OesdkElfLoadExecutable64(OesdkProcess*P,const void*Image,size_t Size,const OesdkElfLoadServices*S,OesdkElfImageInformation*Info){const Ehdr*H;size_t I,Count=0;uintptr_t Low=UINTPTR_MAX,High=0;if(P==NULL||Image==NULL||S==NULL||S->AllocatePages==NULL||S->CopyToPhysical==NULL||Info==NULL||Size<sizeof(Ehdr))return OESDK_STATUS_INVALID_ARGUMENT;H=(const Ehdr*)Image;if(memcmp(H->Ident,"\177ELF",4)!=0||H->Ident[4]!=2U||H->Ident[5]!=1U||H->Type!=2U||H->Machine!=62U||H->Phentsize!=sizeof(Phdr))return OESDK_STATUS_CORRUPT;if(H->Phoff>Size||H->Phnum>(Size-H->Phoff)/sizeof(Phdr))return OESDK_STATUS_CORRUPT;for(I=0;I<H->Phnum;++I){const Phdr*Q=(const Phdr*)((const uint8_t*)Image+H->Phoff+I*sizeof(Phdr));uint64_t FileEnd,VEnd;uintptr_t VBase,Phys;size_t Offset,Pages;OesdkVirtualFlags F=0;OesdkStatus St;if(Q->Type!=PT_LOAD)continue;if(Q->Filesz>Q->Memsz||!AddOk(Q->Offset,Q->Filesz,&FileEnd)||FileEnd>Size||!AddOk(Q->Vaddr,Q->Memsz,&VEnd)||VEnd==0U||VEnd-1U>OESDK_USER_ADDRESS_MAX)return OESDK_STATUS_CORRUPT;VBase=(uintptr_t)(Q->Vaddr&~OESDK_VIRTUAL_PAGE_MASK);Offset=(size_t)(Q->Vaddr-VBase);Pages=(Offset+(size_t)Q->Memsz+OESDK_VIRTUAL_PAGE_SIZE-1U)/OESDK_VIRTUAL_PAGE_SIZE;St=S->AllocatePages(Pages,&Phys,S->Context);if(OESDK_FAILED(St))return St;if(Q->Flags&PF_W)F|=OESDK_VIRTUAL_FLAG_WRITABLE;if(!(Q->Flags&PF_X))F|=OESDK_VIRTUAL_FLAG_NO_EXECUTE;St=OesdkAddressSpaceMap(&P->AddressSpace,VBase,Phys,Pages,F);if(OESDK_FAILED(St))return St;St=S->CopyToPhysical(Phys,(const uint8_t*)Image+Q->Offset,(size_t)Q->Filesz,Offset,S->Context);if(OESDK_FAILED(St))return St;if(VBase<Low)Low=VBase;if(VEnd>High)High=(uintptr_t)VEnd;++Count;}if(Count==0U||!OesdkUserRangeValidate(&P->AddressSpace,(uintptr_t)H->Entry,1U,false))return OESDK_STATUS_CORRUPT;*Info=(OesdkElfImageInformation){(uintptr_t)H->Entry,Count,Low,High};return OESDK_STATUS_SUCCESS;}
