#include <oesdk/address_space.h>
#include <string.h>
static OesdkAddressSpaceId OesdkNextAddressSpaceId = UINT64_C(1);
static bool OesdkRangeEnd(uintptr_t Address, size_t Size, uintptr_t *End) { if (End == NULL || Size > UINTPTR_MAX - Address) return false; *End = Address + Size; return true; }
OesdkStatus OesdkAddressSpaceCreate(uint64_t RootPhysicalAddress, OesdkAddressSpace *Space) { if (Space == NULL || (RootPhysicalAddress & OESDK_VIRTUAL_PAGE_MASK) != 0U) return OESDK_STATUS_INVALID_ARGUMENT; memset(Space,0,sizeof(*Space)); Space->Id=OesdkNextAddressSpaceId++; Space->RootPhysicalAddress=RootPhysicalAddress; Space->Active=true; return OESDK_STATUS_SUCCESS; }
OesdkStatus OesdkAddressSpaceMap(OesdkAddressSpace *Space, uintptr_t VirtualAddress, uintptr_t PhysicalAddress, size_t PageCount, OesdkVirtualFlags Flags) { size_t I; uintptr_t End; size_t Bytes; if (Space==NULL||!Space->Active||PageCount==0U||(VirtualAddress&OESDK_VIRTUAL_PAGE_MASK)||(PhysicalAddress&OESDK_VIRTUAL_PAGE_MASK)) return OESDK_STATUS_INVALID_ARGUMENT; if (PageCount>((size_t)-1)/OESDK_VIRTUAL_PAGE_SIZE) return OESDK_STATUS_INVALID_ARGUMENT; Bytes=PageCount*(size_t)OESDK_VIRTUAL_PAGE_SIZE; if(!OesdkRangeEnd(VirtualAddress,Bytes,&End)||End-1U>OESDK_USER_ADDRESS_MAX) return OESDK_STATUS_INVALID_ARGUMENT; for(I=0;I<Space->MappingCount;++I){uintptr_t ExistingEnd=Space->Mappings[I].VirtualAddress+Space->Mappings[I].PageCount*OESDK_VIRTUAL_PAGE_SIZE;if(VirtualAddress<ExistingEnd&&End>Space->Mappings[I].VirtualAddress)return OESDK_STATUS_ALREADY_EXISTS;} if(Space->MappingCount>=OESDK_ADDRESS_SPACE_MAX_MAPPINGS)return OESDK_STATUS_OUT_OF_MEMORY; Space->Mappings[Space->MappingCount++]=(OesdkAddressSpaceMapping){VirtualAddress,PhysicalAddress,PageCount,Flags|OESDK_VIRTUAL_FLAG_PRESENT|OESDK_VIRTUAL_FLAG_USER}; return OESDK_STATUS_SUCCESS; }
OesdkStatus OesdkAddressSpaceUnmap(OesdkAddressSpace *Space, uintptr_t VirtualAddress, size_t PageCount){size_t I;if(Space==NULL||PageCount==0U)return OESDK_STATUS_INVALID_ARGUMENT;for(I=0;I<Space->MappingCount;++I)if(Space->Mappings[I].VirtualAddress==VirtualAddress&&Space->Mappings[I].PageCount==PageCount){Space->Mappings[I]=Space->Mappings[--Space->MappingCount];return OESDK_STATUS_SUCCESS;}return OESDK_STATUS_NOT_FOUND;}
bool OesdkAddressSpaceQuery(const OesdkAddressSpace *Space, uintptr_t VirtualAddress, uintptr_t *PhysicalAddress, OesdkVirtualFlags *Flags){size_t I;if(Space==NULL||!Space->Active)return false;for(I=0;I<Space->MappingCount;++I){const OesdkAddressSpaceMapping*M=&Space->Mappings[I];uintptr_t End=M->VirtualAddress+M->PageCount*OESDK_VIRTUAL_PAGE_SIZE;if(VirtualAddress>=M->VirtualAddress&&VirtualAddress<End){if(PhysicalAddress)*PhysicalAddress=M->PhysicalAddress+(VirtualAddress-M->VirtualAddress);if(Flags)*Flags=M->Flags;return true;}}return false;}
bool OesdkUserRangeValidate(const OesdkAddressSpace *Space, uintptr_t Address, size_t Size, bool WriteRequested){uintptr_t End,Page;if(Space==NULL||Size==0U||!OesdkRangeEnd(Address,Size,&End)||End<=Address||End-1U>OESDK_USER_ADDRESS_MAX)return false;Page=Address&~(uintptr_t)OESDK_VIRTUAL_PAGE_MASK;while(Page<End){OesdkVirtualFlags Flags=0;if(!OesdkAddressSpaceQuery(Space,Page,NULL,&Flags)||(Flags&OESDK_VIRTUAL_FLAG_PRESENT)==0U||(Flags&OESDK_VIRTUAL_FLAG_USER)==0U||(WriteRequested&&(Flags&OESDK_VIRTUAL_FLAG_WRITABLE)==0U))return false;if(Page>UINTPTR_MAX-OESDK_VIRTUAL_PAGE_SIZE)return false;Page+=OESDK_VIRTUAL_PAGE_SIZE;}return true;}
